name: LockIP
main: iplock.iplock
author: Sgt_Tailor
authors: [Sgt_Tailor,Runemoro]
description: lock ip
version: 0.8
commands:
    login:
        description: writes a players Ip to the yml.
        usage: /login <password>
    setpassword:
        description: encrypts and saves a users password.
        usage: /setpassword <password>
    register:
        description: sets the password and logs you in.
        usage: /register <password>
    safeip:
        permission: iplock.safeip
        description: regards the ip linked to the player name as safe.
        usage: /safeip <password>
    lockip:
        description: lock an ip to an username.
        usage: /lockip <password>
        permission: lockip.lockown
    reset:
        permission: iplock.reset.password
        usage: /reset <Player>
permissions:
    iplock.reset.password:
        default: OP
        description: allows a user to reset someone else his password
    iplock.lockown:
        default: false
        description: allows a user to lock their ip.
    iplock.safeip:
        default: true
        description: allows a user to do /safeip